version: 2

updates:
  ##################################################
  # NPM / Node Projects
  ##################################################

- package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "npm"
    directory: "/zmscitizenview"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "npm"
    directory: "/zmscitizenapi"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "npm"
    directory: "/zmsapi"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "npm"
    directory: "/zmsadmin"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "npm"
    directory: "/zmsstatistic"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "npm"
    directory: "/zmsticketprinter"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "npm"
    directory: "/zmscalldisplay"
    schedule:
      interval: "weekly"
    target-branch: "next"


  ##################################################
  # Composer Projects
  ##################################################

- package-ecosystem: "composer"
    directory: "/mellon"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmsadmin"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmsapi"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmscalldisplay"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmscitizenapi"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmsclient"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmsdb"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmsdldb"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmsentities"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmsmessaging"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmsslim"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmsstatistic"
    schedule:
      interval: "weekly"
    target-branch: "next"

- package-ecosystem: "composer"
    directory: "/zmsticketprinter"
    schedule:
      interval: "weekly"
    target-branch: "next"
