services:
  web:
    container_name: zms-web
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - ..:/var/www/html:cached
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini:ro
    ports:
      - "8090:80"
      - "8091:443"
    env_file:
      - .env
    depends_on:
      - db
      - keycloak
    networks:
      - default

  db:
    image: mariadb:10.11
    container_name: zms-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5
    container_name: zms-phpmyadmin
    restart: unless-stopped
    ports:
      - "8036:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_HOST=zms-db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=25600M
    depends_on:
      - db

  refarch-gateway:
    image: ghcr.io/it-at-m/refarch/refarch-gateway:1.7.0
    container_name: zms-refarch-gateway
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=no-security
      - WEBCOMPONENT_URI=http://localhost:8080
    volumes:
      - ./local-gateway-application.yml:/deployments/application.yml:ro
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.3@sha256:5a236ae4dd8ece77490115bace15a11a4d15e9cbcf58a490b95a7da2cd71d32a
    container_name: zms-keycloak
    hostname: keycloak.local
    command:
      - start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_PORT=8080
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_DB=dev-file
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/plugins:/opt/keycloak/providers/
    networks:
      default:
        aliases:
          - keycloak.local
    restart: unless-stopped

  init-keycloak:
    image: klg71/keycloakmigration:0.2.125@sha256:a326d3e50e2a35b70a3cf3a5d33288af9bcba27fef89146a2107622583e34231
    depends_on:
      keycloak:
        condition: service_started
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
      - BASEURL=http://keycloak:8080/auth
      - WAIT_FOR_KEYCLOAK=true
      - FAIL_ON_UNDEFINED_VARIABLES=true
      - KEYCLOAK_CHANGELOG=/migration/keycloak-changelog.yml
    volumes:
      - ../.resources/keycloak/migration:/migration
    networks:
      - default
    restart: "no"

volumes:
  db-data:
